from typing import Any, Callable, TypeAlias, TypeVar, overload
from typing_extensions import dataclass_transform
from _typeshed import DataclassInstance as _DataclassInstance
from pydantic import BaseModel as _PydanticBaseModel


_T = TypeVar("_T")

MODEL_SCHEMA_KIND_UNKNOWN: int
MODEL_SCHEMA_KIND_GN_FAST_DATAMODEL: int
MODEL_SCHEMA_KIND_PYTHON_DATACLASS: int
MODEL_SCHEMA_KIND_PYDANTIC_BASEMODEL: int
MODEL_SCHEMA_KIND_PYDANTIC_TYPEADAPTER: int
MODEL_SCHEMA_KIND_NAMES: dict[int, str]


class _ModelAccessor:
    def dump(self) -> dict[str, Any]: ...
    def dump_json(self, **kwargs: Any) -> str: ...
    def copy(self, *, update: dict[str, Any] | None = None, deep: bool = False) -> Any: ...

    @property
    def fields_set(self) -> set[str]: ...

    @staticmethod
    def validate(model_class: type[_T], obj: Any, **kwargs: Any) -> _T: ...

    @staticmethod
    def validate_json(model_class: type[_T], json_data: str | bytes | bytearray, **kwargs: Any) -> _T: ...

    @staticmethod
    def validate_strings(model_class: type[_T], obj: Any, **kwargs: Any) -> _T: ...

    @staticmethod
    def schema(model_class: type, **kwargs: Any) -> dict[str, Any]: ...

    @staticmethod
    def rebuild(model_class: type, **kwargs: Any) -> bool | None: ...

    @staticmethod
    def fields(model_class: type) -> Any: ...

    @staticmethod
    def computed_fields(model_class: type) -> dict[str, Any]: ...

    @staticmethod
    def config(model_class: type) -> dict[str, Any]: ...


class FastDataModelValidationError(ValueError): ...


ModelPayload: TypeAlias = _PydanticBaseModel | _DataclassInstance


@overload
@dataclass_transform(kw_only_default=False)
def dataclass(_cls: type[_T], **kwargs: Any) -> type[_T]: ...


@overload
@dataclass_transform(kw_only_default=False)
def dataclass(_cls: None = None, **kwargs: Any) -> Callable[[type[_T]], type[_T]]: ...


@overload
@dataclass_transform(kw_only_default=False)
def FastDataModel(_cls: type[_T], **kwargs: Any) -> type[_T]: ...


@overload
@dataclass_transform(kw_only_default=False)
def FastDataModel(_cls: None = None, **kwargs: Any) -> Callable[[type[_T]], type[_T]]: ...


@overload
@dataclass_transform(kw_only_default=False)
def BaseModel(_cls: type[_T], **kwargs: Any) -> type[_T]: ...


@overload
@dataclass_transform(kw_only_default=False)
def BaseModel(_cls: None = None, **kwargs: Any) -> Callable[[type[_T]], type[_T]]: ...


def is_fast_model_type(value: Any) -> bool: ...
def is_fast_model_instance(value: Any) -> bool: ...
def is_pydantic_model_type(value: Any) -> bool: ...
def is_pydantic_model_instance(value: Any) -> bool: ...
def is_dataclass_model_type(value: Any) -> bool: ...
def is_dataclass_model_instance(value: Any) -> bool: ...
def is_model_type(value: Any) -> bool: ...
def is_model_instance(value: Any) -> bool: ...
def model_kind(value: Any) -> str: ...
def model_schema_kind(value: Any) -> int: ...
def model_schema_name(value: Any) -> str: ...
def model_validate(model_class: type[_T], obj: Any, **kwargs: Any) -> _T: ...
def model_validate_instance(obj: Any) -> None: ...
def model_validate_dump(obj: Any) -> dict[str, Any]: ...
def model_dump(obj: Any) -> dict[str, Any]: ...
