gn_core_domains = (
    'core',
    'gw',
    'gwis',
    'abs'
)

gn_sys_domains = (
    'gn',
    'sys'
)

gn_domains = (
    'com',
    'net',
    'gov'
)

base_gnrequest_transport = 'gn:quik:net'
base_gnrequest_method = 'get'
base_gnrequest_route = 'gn:net'

common_gnrequest_transports = { # max 15
    'gn:quik:dev': 0,
    'gn:raw:dev': 1,
}


common_gnrequest_methods = { # max 256
    'get': 0,
    'post': 1,
    'put': 2,
    'delete': 3,
    'patch': 4,
    'gn:sys': 7,
}

common_gnrequest_routes = { # max 255
}

common_gnrequest_dataTypes = { # max 16
    'static': 1,
    'api': 2,
    'img': 3,
    'fat': 4,
    'stream': 5
}

base_gnrequest_inType = None


tablex_legacy_mime_type_to_inType = {
    'text/html': 'html',
    'application/xhtml+xml': 'html',
    'text/css': 'css',
    'application/javascript': 'js',
    'text/javascript': 'js',
    'application/ecmascript': 'js',
    'text/ecmascript': 'js',
    'application/typescript': 'ts',
    'text/typescript': 'ts',
    'text/tsx': 'tsx',
    'text/jsx': 'jsx',
    'image/svg+xml': 'svg',
    'text/plain': 'txt',
    'text/x-log': 'log',
    'application/xml': 'xml',
    'text/xml': 'xml',
    'application/pdf': 'pdf',
    'application/wasm': 'wasm',
    'text/x-python': 'py',
    'application/x-python-code': 'py',
    'text/x-c': 'c',
    'text/x-chdr': 'h',
    'text/x-c++': 'cpp',
    'text/x-c++hdr': 'hpp',
    'text/x-rust': 'rs',
    'text/x-go': 'go',
    'text/x-java-source': 'java',
    'text/x-kotlin': 'kt',
    'text/x-swift': 'swift',
    'text/x-csharp': 'cs',
    'application/x-httpd-php': 'php',
    'text/x-ruby': 'rb',
    'text/x-lua': 'lua',
    'application/x-sh': 'sh',
    'text/x-shellscript': 'sh',
    'text/x-powershell': 'ps1',
    'application/sql': 'sql',
    'application/x-protobuf': 'proto',
    'application/graphql': 'graphql',
    'text/x-asm': 'asm',
    'application/x-bat': 'bat',
    'application/x-cmd': 'cmd',
    'application/vnd.microsoft.portable-executable': 'exe',
    'application/x-msdownload': 'dll',
    'application/x-sharedlib': 'so',
    'application/x-mach-binary': 'dylib',
    'application/x-object': 'obj',
    'application/java-vm': 'class',
    'application/java-archive': 'jar',
    'application/vnd.android.package-archive': 'apk',
    'image/png': 'png',
    'image/jpeg': 'jpg',
    'image/webp': 'webp',
    'image/avif': 'avif',
    'image/tiff': 'tif',
    'image/x-icon': 'ico',
    'image/vnd.microsoft.icon': 'ico',
    'audio/wav': 'wav',
    'audio/x-wav': 'wav',
    'audio/flac': 'flac',
    'audio/aac': 'aac',
    'audio/mp4': 'm4a',
    'audio/ogg': 'ogg',
    'audio/opus': 'opus',
    'video/mp4': 'mp4',
    'video/x-matroska': 'mkv',
    'video/webm': 'webm',
    'video/quicktime': 'mov',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'pptx',
    'font/ttf': 'ttf',
    'font/otf': 'otf',
    'font/woff': 'woff',
    'font/woff2': 'woff2',
    'application/vnd.sqlite3': 'sqlite',
    'application/x-sqlite3': 'sqlite',
    'application/vnd.apache.parquet': 'parquet',
    'application/x-npy': 'npy',
    'application/x-npz': 'npz',
    'application/x-pem-file': 'pem',
    'application/pem-certificate-chain': 'pem',
    'text/x-pem-file': 'pem'
}

tablex_legacy_inType_to_mime_type = {
    'html': 'text/html',
    'css': 'text/css',
    'js': 'application/javascript',
    'ts': 'application/typescript',
    'tsx': 'text/tsx',
    'jsx': 'text/jsx',
    'svg': 'image/svg+xml',
    'txt': 'text/plain',
    'xml': 'application/xml',
    'log': 'text/x-log',
    'pdf': 'application/pdf',
    'wasm': 'application/wasm',
    'py': 'text/x-python',
    'c': 'text/x-c',
    'h': 'text/x-chdr',
    'cpp': 'text/x-c++',
    'hpp': 'text/x-c++hdr',
    'rs': 'text/x-rust',
    'go': 'text/x-go',
    'java': 'text/x-java-source',
    'kt': 'text/x-kotlin',
    'swift': 'text/x-swift',
    'cs': 'text/x-csharp',
    'php': 'application/x-httpd-php',
    'rb': 'text/x-ruby',
    'lua': 'text/x-lua',
    'sh': 'application/x-sh',
    'ps1': 'text/x-powershell',
    'sql': 'application/sql',
    'proto': 'application/x-protobuf',
    'graphql': 'application/graphql',
    'asm': 'text/x-asm',
    'bat': 'application/x-bat',
    'cmd': 'application/x-cmd',
    'exe': 'application/vnd.microsoft.portable-executable',
    'dll': 'application/x-msdownload',
    'so': 'application/x-sharedlib',
    'dylib': 'application/x-mach-binary',
    'obj': 'application/x-object',
    'class': 'application/java-vm',
    'jar': 'application/java-archive',
    'apk': 'application/vnd.android.package-archive',
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'webp': 'image/webp',
    'avif': 'image/avif',
    'tif': 'image/tiff',
    'ico': 'image/x-icon',
    'wav': 'audio/wav',
    'flac': 'audio/flac',
    'aac': 'audio/aac',
    'm4a': 'audio/mp4',
    'ogg': 'audio/ogg',
    'opus': 'audio/opus',
    'mp4': 'video/mp4',
    'mkv': 'video/x-matroska',
    'webm': 'video/webm',
    'mov': 'video/quicktime',
    'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'ttf': 'font/ttf',
    'otf': 'font/otf',
    'woff': 'font/woff',
    'woff2': 'font/woff2',
    'sqlite': 'application/vnd.sqlite3',
    'parquet': 'application/vnd.apache.parquet',
    'npy': 'application/x-npy',
    'npz': 'application/x-npz',
    'pem': 'application/x-pem-file'
}

tablex_file_extension_to_inType = {
    'html': 'html',
    'htm': 'html',
    'css': 'css',
    'js': 'js',
    'ts': 'ts',
    'tsx': 'tsx',
    'jsx': 'jsx',
    'svg': 'svg',
    'txt': 'txt',
    'xml': 'xml',
    'log': 'log',
    'pdf': 'pdf',
    'wasm': 'wasm',
    'py': 'py',
    'c': 'c',
    'h': 'h',
    'cpp': 'cpp',
    'cc': 'cpp',
    'cxx': 'cpp',
    'hpp': 'hpp',
    'hh': 'hpp',
    'hxx': 'hpp',
    'rs': 'rs',
    'go': 'go',
    'java': 'java',
    'kt': 'kt',
    'kts': 'kt',
    'swift': 'swift',
    'cs': 'cs',
    'php': 'php',
    'rb': 'rb',
    'lua': 'lua',
    'sh': 'sh',
    'bash': 'sh',
    'ps1': 'ps1',
    'sql': 'sql',
    'proto': 'proto',
    'graphql': 'graphql',
    'gql': 'graphql',
    'asm': 'asm',
    's': 'asm',
    'bat': 'bat',
    'cmd': 'cmd',
    'exe': 'exe',
    'dll': 'dll',
    'so': 'so',
    'dylib': 'dylib',
    'obj': 'obj',
    'o': 'obj',
    'class': 'class',
    'jar': 'jar',
    'apk': 'apk',
    'png': 'png',
    'jpg': 'jpg',
    'jpeg': 'jpg',
    'jpe': 'jpg',
    'webp': 'webp',
    'avif': 'avif',
    'tif': 'tif',
    'tiff': 'tif',
    'ico': 'ico',
    'wav': 'wav',
    'flac': 'flac',
    'aac': 'aac',
    'm4a': 'm4a',
    'ogg': 'ogg',
    'opus': 'opus',
    'mp4': 'mp4',
    'mkv': 'mkv',
    'webm': 'webm',
    'mov': 'mov',
    'docx': 'docx',
    'xlsx': 'xlsx',
    'pptx': 'pptx',
    'ttf': 'ttf',
    'otf': 'otf',
    'woff': 'woff',
    'woff2': 'woff2',
    'sqlite': 'sqlite',
    'sqlite3': 'sqlite',
    'parquet': 'parquet',
    'npy': 'npy',
    'npz': 'npz',
    'pem': 'pem',
}

common_inTypes = { # max 256
    'html': 0,
    'css': 1,
    'js': 2,
    'ts': 3,
    'tsx': 4,
    'jsx': 5,
    'svg': 6,
    'txt': 7,
    'xml': 8,
    'log': 9,
    'pdf': 10,
    'wasm': 11,
    'py': 12,
    'c': 13,
    'h': 14,
    'cpp': 15,
    'hpp': 16,
    'rs': 17,
    'go': 18,
    'java': 19,
    'kt': 20,
    'swift': 21,
    'cs': 22,
    'php': 23,
    'rb': 24,
    'lua': 25,
    'sh': 26,
    'ps1': 27,
    'sql': 28,
    'proto': 29,
    'graphql': 30,
    'asm': 31,
    'bat': 32,
    'cmd': 33,
    'exe': 34,
    'dll': 35,
    'so': 36,
    'dylib': 37,
    'obj': 38,
    'class': 39,
    'jar': 40,
    'apk': 41,
    'png': 42,
    'jpg': 43,
    'webp': 44,
    'avif': 45,
    'tif': 46,
    'ico': 47,
    'wav': 48,
    'flac': 49,
    'aac': 50,
    'm4a': 51,
    'ogg': 52,
    'opus': 53,
    'mp4': 54,
    'mkv': 55,
    'webm': 56,
    'mov': 57,
    'docx': 58,
    'xlsx': 59,
    'pptx': 60,
    'ttf': 61,
    'otf': 62,
    'woff': 63,
    'woff2': 64,
    'sqlite': 65,
    'parquet': 66,
    'npy': 67,
    'npz': 68,
    'pem': 69,
}

"""
common_inTypes_compression_support:
(
    1. on/off
    2. use pretrained map
    3. alg (0 = zstd,...)
    4. level of compression (1 - 3)
)
"""
common_inTypes_compression_support = {
    common_inTypes['html']: (1, 0, 0, 2),
    common_inTypes['css']: (1, 0, 0, 2),
    common_inTypes['js']: (1, 0, 0, 2),
    common_inTypes['ts']: (1, 0, 0, 2),
    common_inTypes['tsx']: (1, 0, 0, 2),
    common_inTypes['jsx']: (1, 0, 0, 2),
    common_inTypes['svg']: (1, 0, 0, 2),
    common_inTypes['txt']: (1, 0, 0, 2),
    common_inTypes['xml']: (1, 0, 0, 2),
    common_inTypes['log']: (1, 0, 0, 2),
    common_inTypes['pdf']: (0, 0, 0, 0),
    common_inTypes['wasm']: (1, 0, 0, 2),
    common_inTypes['py']: (1, 0, 0, 2),
    common_inTypes['c']: (1, 0, 0, 2),
    common_inTypes['h']: (1, 0, 0, 2),
    common_inTypes['cpp']: (1, 0, 0, 2),
    common_inTypes['hpp']: (1, 0, 0, 2),
    common_inTypes['rs']: (1, 0, 0, 2),
    common_inTypes['go']: (1, 0, 0, 2),
    common_inTypes['java']: (1, 0, 0, 2),
    common_inTypes['kt']: (1, 0, 0, 2),
    common_inTypes['swift']: (1, 0, 0, 2),
    common_inTypes['cs']: (1, 0, 0, 2),
    common_inTypes['php']: (1, 0, 0, 2),
    common_inTypes['rb']: (1, 0, 0, 2),
    common_inTypes['lua']: (1, 0, 0, 2),
    common_inTypes['sh']: (1, 0, 0, 2),
    common_inTypes['ps1']: (1, 0, 0, 2),
    common_inTypes['sql']: (1, 0, 0, 2),
    common_inTypes['proto']: (1, 0, 0, 2),
    common_inTypes['graphql']: (1, 0, 0, 2),
    common_inTypes['asm']: (1, 0, 0, 2),
    common_inTypes['bat']: (1, 0, 0, 2),
    common_inTypes['cmd']: (1, 0, 0, 2),
    common_inTypes['exe']: (1, 0, 0, 2),
    common_inTypes['dll']: (1, 0, 0, 2),
    common_inTypes['so']: (1, 0, 0, 2),
    common_inTypes['dylib']: (1, 0, 0, 2),
    common_inTypes['obj']: (1, 0, 0, 2),
    common_inTypes['class']: (1, 0, 0, 2),
    common_inTypes['jar']: (0, 0, 0, 0),
    common_inTypes['apk']: (0, 0, 0, 0),
    common_inTypes['png']: (0, 0, 0, 0),
    common_inTypes['jpg']: (0, 0, 0, 0),
    common_inTypes['webp']: (0, 0, 0, 0),
    common_inTypes['avif']: (0, 0, 0, 0),
    common_inTypes['tif']: (0, 0, 0, 0),
    common_inTypes['ico']: (0, 0, 0, 0),
    common_inTypes['wav']: (1, 0, 0, 2),
    common_inTypes['flac']: (0, 0, 0, 0),
    common_inTypes['aac']: (0, 0, 0, 0),
    common_inTypes['m4a']: (0, 0, 0, 0),
    common_inTypes['ogg']: (0, 0, 0, 0),
    common_inTypes['opus']: (0, 0, 0, 0),
    common_inTypes['mp4']: (0, 0, 0, 0),
    common_inTypes['mkv']: (0, 0, 0, 0),
    common_inTypes['webm']: (0, 0, 0, 0),
    common_inTypes['mov']: (0, 0, 0, 0),
    common_inTypes['docx']: (0, 0, 0, 0),
    common_inTypes['xlsx']: (0, 0, 0, 0),
    common_inTypes['pptx']: (0, 0, 0, 0),
    common_inTypes['ttf']: (1, 0, 0, 2),
    common_inTypes['otf']: (1, 0, 0, 2),
    common_inTypes['woff']: (0, 0, 0, 0),
    common_inTypes['woff2']: (0, 0, 0, 0),
    common_inTypes['sqlite']: (1, 0, 0, 2),
    common_inTypes['parquet']: (0, 0, 0, 0),
    common_inTypes['npy']: (1, 0, 0, 2),
    common_inTypes['npz']: (0, 0, 0, 0),
    common_inTypes['pem']: (1, 0, 0, 2),
}


# legacy
from ..gwis.values import tablex_gwis_object_types_int_to_str as _tablex_gwis_object_types_int_to_str
tablex_gwiso_type_int_to_str = _tablex_gwis_object_types_int_to_str

common_gnrequest_compressTypes = { # max 16
    'none': 0,
    'zstd': 1
}